apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  # Las variables en un Secret de K8s deben estar codificadas en Base64
  jwt-secret: {{ .Values.global.jwtSecret | b64enc | quote }}
  
  database-url: {{ printf "postgresql+asyncpg://%s:%s@%s:%d/%s" 
      .Values.database.user 
      (eq .Values.global.environment "local" | ternary .Values.database.password .Values.database.passwordPlaintext)
      (eq .Values.global.environment "local" | ternary "db-global" .Values.database.host)
      (eq .Values.global.environment "local" | ternary 5432 (int .Values.database.port))
      .Values.database.dbName | b64enc | quote }}

  sitrack-user: {{ (index .Values.backends "ms-mantencion").sitrackUser | default "" | b64enc | quote }}
  sitrack-pass: {{ (index .Values.backends "ms-mantencion").sitrackPass | default "" | b64enc | quote }}
