apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchdog-sa
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watchdog-role
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watchdog-rolebinding
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: watchdog-sa
  namespace: default
roleRef:
  kind: Role
  name: watchdog-role
  apiGroup: rbac.authorization.k8s.io
